### ISSUE TITLE
Tag current version as 2020-07-22

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/AllenInstituteMockLIMS#1]
`2020-07-22` correspond to the date of the latest commit in `master`

You could use the following commands:

```
release=2020-07-22
git tag --sign -m "AllenInstituteMockLIMS ${release}" ${release} master
git push ${release}
```

If you don't have a GPG key, see https://help.github.com/articles/generating-a-new-gpg-key/

**Comment by allemangD** [comment]
This has been completed; the tag is visible [here](https://github.com/KitwareMedical/AllenInstituteMockLIMS/releases).
